const router = require('express').Router();
const axios = require('axios');
const { authenticate } = require('../middleware/auth');
const logger = require('../utils/logger');

router.post('/chat', authenticate, async (req, res) => {
  // Read 'message' exactly as sent by the frontend
  const { message } = req.body;
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey || apiKey === 'your_gemini_key') {
    return res.status(503).json({ 
      error: 'AI connection unavailable. Ensure your GEMINI_API_KEY is configured in your Render Environment Variables.' 
    });
  }

  try {
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        contents: [{ role: "user", parts: [{ text: message }] }],
        systemInstruction: {
          parts: [{ text: 'You are the Chayil SecureX AI Security Assistant. You specialize in cybersecurity, GRC orchestration, and threat intelligence. Provide extremely accurate, authoritative, and concise responses.' }]
        }
      },
      {
        headers: { 'Content-Type': 'application/json' }
      }
    );

    // Parse out the exact text generated by Gemini
    const reply = response.data.candidates?.[0]?.content?.parts?.[0]?.text || 'I could not generate a response.';
    
    // The frontend explicitly expects response.data.reply
    res.json({ reply });
  } catch (error) {
    logger.error('Gemini API Error:', error.response?.data || error.message);
    res.status(500).json({ error: 'Failed to communicate with Google Gemini AI provider.' });
  }
});

module.exports = router;
